# Generated by Django 4.0.4 on 2022-06-29 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Сalculation_of_flange_bolts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название вашего расчета', max_length=30, verbose_name='Название расчета')),
                ('count_bolts', models.IntegerField(help_text='Введите количество болтов', max_length=3, verbose_name='Количество болтов')),
                ('bolt_strength_class', models.CharField(help_text='Выберите класс прочности болтов', max_length=4, verbose_name='Класс прочности болтов')),
                ('diametr_bolta', models.IntegerField(help_text='Введите диаметр болта', max_length=3, verbose_name='Диаметр болта')),
                ('circle_diameter', models.IntegerField(help_text='Введите диаметр окружности, по которому расположены болты', verbose_name='Диаметр окружности')),
                ('stress_N', models.IntegerField(help_text='Введите продольную силу N в тс', verbose_name='Продольная сила N в кг')),
                ('stress_M', models.IntegerField(help_text='Введите момент M в тс*м', verbose_name='Момент M в тс*м')),
                ('on_bolt', models.BooleanField(help_text='Установлены ли на шпильках', verbose_name='Установка на шпильки')),
                ('foundation_bolts', models.BooleanField(help_text='Фундаментные болты', verbose_name='Фундаментные болты')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
